feat: rich text styles (WIP)
technologiestiftung/oeffentliches-gestalten-docusaurus pull request #9
Opened 2023-01-25 14:26 UTC by dnsos

This PR adds sytles for the markdown content using Tailwind's `prose` plugin.

2023-01-26 13:58 UTC, vogelino requested changes
Amazing work. It looks very well balanced :)

I noticed however that the list elements differ from the designs. They should be displayed outside of the container boundarie. See:
![CleanShot 2023-01-26 at 14 58 20](https://user-images.githubusercontent.com/2759340/214854246-0fab5444-b93f-4fa7-8c60-63eaec46aea9.png)

2023-01-27 13:44 UTC, dnsos commented
Thanks for the review @vogelino. I have adjusted the elements to the design now.

I've found that it looks best to have _all_ special elements (lists, checkboxes, blockquotes, hints) to be outside of the the main grid then. On smaller screens (< 768px) all of them slide into the grid to avoid too much horizontal padding.

2023-01-27 14:14 UTC, vogelino commented
@dnsos It looks great! Thx for the changes! 

![boat-ship-it-gif](https://user-images.githubusercontent.com/2759340/215107851-65d20532-c810-45ec-815f-b9b495fcc30a.gif)

2023-01-27 14:15 UTC, vogelino approved these changes

2023-01-27 14:21 UTC, merged